from __future__ import annotations

ALL_STAGES = {
    "INITIALIZED",
    "MASTER_PROMPT_SAVED",
    "GOAL_SPEC_REQUIRED",
    "GOAL_SPEC_READY",
    "CENSUS_REQUIRED",
    "CENSUS_READY",
    "EVIDENCE_CLASSIFICATION_REQUIRED",
    "EVIDENCE_READY",
    "INVENTORY_BUILD_REQUIRED",
    "INVENTORY_READY",
    "INVARIANT_EXTRACTION_REQUIRED",
    "INVARIANTS_READY",
    "PATCHLET_COMPILATION_REQUIRED",
    "PATCHLETS_READY",
    "PATCHLET_EXECUTION_IN_PROGRESS",
    "PATCHLET_EXECUTION_COMPLETE",
    "TRANSACTION_VERIFICATION_REQUIRED",
    "TRANSACTION_VERIFICATION_COMPLETE",
    "GLOBAL_VERIFICATION_REQUIRED",
    "GLOBAL_VERIFICATION_COMPLETE",
    "FAILURE_CLASSIFICATION_REQUIRED",
    "REPAIR_PLANNING_REQUIRED",
    "REPAIR_PLAN_READY",
    "REPAIR_APPLICATION_REQUIRED",
    "REPAIR_IN_PROGRESS",
    "PARTIAL_REDISCOVERY_REQUIRED",
    "FULL_REDISCOVERY_REQUIRED",
    "INVENTORY_REBUILD_REQUIRED",
    "PATCHLET_REGENERATION_REQUIRED",
    "GLOBAL_REVERIFY_REQUIRED",
    "DONE",
    "ORCHESTRATOR_ABORTED",
}

TERMINAL_SUCCESS = "DONE"
TERMINAL_ABORT = "ORCHESTRATOR_ABORTED"


def assert_stage(stage: str) -> None:
    if stage not in ALL_STAGES:
        raise ValueError(f"Unknown workflow stage: {stage}")
